# This is Reflektive's convention on Ruby/Rails coding style and best practices.
#
# This repository should always be free of offenses against the rubocop
# configuration herein. These are also the rules run by Hound.

AllCops:
  Exclude:
    - 'client/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'lib/tasks/migrations/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6.6
  #
  # All cops are disabled by default.
  # They are individually enabled in the inherited files.
  #
  DisabledByDefault: true

Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

# Layout/BlockEndNewline:
#   Enabled: true

# Layout/CaseIndentation:
#   Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

# Layout/DotPosition:
#   Enabled: true

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBeginBody:
  Enabled: true

# Layout/EmptyLinesAroundBlockBody:
#   Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

# Layout/EmptyLinesAroundMethodBody:
#   Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

# Layout/FirstParameterIndentation:
#   Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/AssignmentIndentation:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

# Layout/IndentationWidth:
#   Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: false

# Layout/MultilineBlockLayout:
#   Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

# Layout/MultilineOperationIndentation:
#   Enabled: true

Layout/RescueEnsureAlignment:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceBeforeSemicolon:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: true

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true

# Layout/SpaceInsideBrackets:
#   Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: true

# Lint/BlockAlignment:
#   Enabled: true

Lint/BooleanSymbol:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Lint/Debugger:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EmptyWhen:
  Enabled: true

Layout/EndAlignment:
  Enabled: false

Style/EndBlock:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FlipFlop:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

# Lint/HandleExceptions:
#   Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/IneffectiveAccessModifier:
  Enabled: true

Lint/InheritException:
  Enabled: true

Lint/InterpolationCheck:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/MultipleComparison:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

# Lint/NonLocalExitFromIterator:
#   Enabled: true

# Lint/ParenthesesAsGroupedExpression:
#   Enabled: true

Lint/PercentStringArray:
  Enabled: true

Lint/PercentSymbolArray:
  Enabled: true

Lint/RandOne:
  Enabled: true

Lint/RedundantWithIndex:
  Enabled: true

Lint/RedundantWithObject:
  Enabled: true

Lint/RegexpAsCondition:
  Enabled: true

Lint/RequireParentheses:
  Enabled: false

# Lint/RescueException:
#   Enabled: true

Lint/RescueType:
  Enabled: true

# Lint/RescueWithoutErrorClass:
#   Enabled: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Lint/ScriptPermission:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

# Lint/ShadowingOuterLocalVariable:
#   Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

# Lint/UnderscorePrefixedVariableName:
#   Enabled: true

# Lint/UnifiedInteger:
#   Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantRequireStatement:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

# Lint/UnusedBlockArgument:
#   Enabled: true

# Lint/UnusedMethodArgument:
#   Enabled: true

# Lint/UriEscapeUnescape:
#   Enabled: true

# Lint/UriRegexp:
#   Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/UselessElseWithoutRescue:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Lint/Void:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/ConstantName:
  Enabled: false

Naming/FileName:
  Enabled: true

Naming/HeredocDelimiterCase:
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: true

# Naming/MethodName:
#   Enabled: true

Naming/PredicateName:
  Enabled: false

# Naming/VariableName:
#   Enabled: true

# Naming/VariableNumber:
#   Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

# Security/YAMLLoad:
#   Enabled: true

# Style/Alias:
#   Enabled: true

Style/AndOr:
  Enabled: false

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BlockDelimiters:
  Enabled: false

# Style/BracesAroundHashParameters:
#   Enabled: true

# Style/CaseEquality:
#   Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: true

Style/ClassMethods:
  Enabled: true

# Style/ClassVars:
#   Enabled: true

Style/CollectionMethods:
  Enabled: false

Style/ColonMethodCall:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/CommentedKeyword:
  Enabled: true

# Style/ConditionalAssignment:
#   Enabled: true

Style/Copyright:
  Enabled: false

# Style/DateTime:
#   Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/Dir:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachForSimpleLoop:
  Enabled: true

# Style/EachWithObject:
#   Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/EndBlock:
  Enabled: true

Style/EvenOdd:
  Enabled: true

# Style/For:
#   Enabled: true

# Style/FormatString:
#   Enabled: true

Style/FormatStringToken:
  Enabled: true
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

# Style/GlobalVars:
#   Enabled: true

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: true

# Style/IdenticalConditionalBranches:
#   Enabled: true

# Style/IfInsideElse:
#   Enabled: true

Style/IfUnlessModifier:
  Enabled: false

# Style/IfUnlessModifierOfIfUnless:
#   Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: false

Style/InfiniteLoop:
  Enabled: true

Style/InlineComment:
  Enabled: false

Style/InverseMethods:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: true

# Style/LineEndConcatenation:
#   Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: true

# Style/MethodMissing:
#   Enabled: true

Style/MinMax:
  Enabled: true

Style/MissingElse:
  Enabled: false

Style/MixinGrouping:
  Enabled: true

Style/MixinUsage:
  Enabled: true

# Style/ModuleFunction:
#   Enabled: true

# Style/MultilineBlockChain:
#   Enabled: true

# Style/MultilineIfModifier:
#   Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

# Style/MultilineTernaryOperator:
#   Enabled: true

Style/MultipleComparison:
  Enabled: true

# Style/MutableConstant:
#   Enabled: true

# Style/NegatedIf:
#   Enabled: true

Style/NegatedWhile:
  Enabled: true

# Style/NestedModifier:
#   Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: false

# Style/NestedTernaryOperator:
#   Enabled: true

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: true

# Style/NonNilCheck:
#   Enabled: true

# Style/Not:
#   Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

# Style/NumericLiterals:
#   Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/OneLineConditional:
  Enabled: true

# Style/OptionHash:
#   Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/ParallelAssignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PercentQLiterals:
  Enabled: true

Style/PerlBackrefs:
  Enabled: true

# Style/PreferredHashMethods:
#   Enabled: true

# Style/Proc:
#   Enabled: true

Style/RaiseArgs:
  Enabled: true

# Style/RedundantBegin:
#   Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: false

# Style/RedundantSelf:
#   Enabled: true

# Style/RegexpLiteral:
#   Enabled: true

# Style/RescueModifier:
#   Enabled: true

# Style/ReturnNil:
#   Enabled: true

# Style/SafeNavigation:
#   Enabled: true

# Style/SelfAssignment:
#   Enabled: true

Style/Semicolon:
  Enabled: true

Style/Send:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

# Style/SingleLineMethods:
#   Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StderrPuts:
  Enabled: true

# Style/StringLiterals:
#   Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/StructInheritance:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/SymbolLiteral:
  Enabled: true

# Style/SymbolProc:
#   Enabled: true

# Style/TernaryParentheses:
#   Enabled: true

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/RedundantCapitalW:
  Enabled: true

# Style/UnneededInterpolation:
#   Enabled: true

Style/RedundantPercentQ:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: true

# Style/ZeroLengthPredicate:
#   Enabled: true
